### ISSUE TITLE
Error setting field value from another plugin

### ISSUE THREAD

**Issue by goraxan** [chasegiunta/craft-jason#73]
It's not possible to set a Jason field value programmatically from another plugin (calling the `setFieldValue` method on an element for this field), you get the following error `json_decode() expects parameter 1 to be string, array given` in the method `public function validateIsJSON(ElementInterface $element, array $params = null)`.

Apparently it is due to how the normalizeValue method is implemented (the request is identified as a site request and is returned as an array causing the validateIsJSON method to fail). I've fixed it by checking if it's an action request:
```
    public function normalizeValue($value, ElementInterface $element = null)
    {
        if (Craft::$app->request->getIsSiteRequest() && 
        !Craft::$app->request->getIsActionRequest()) {
            return json_decode($value, true);
        } else {
            return $value;
        }
    }
```

This is the command causing the error:
```
$user = User::find()->email('whateveremail')->one();
$user->setFieldValue('myFieldName', 'jsoninstringformat');

Craft::$app->getElements()->saveElement($user); <---- Error
```

This is the stacktrace with the error:
```
2020-03-12 05:38:12 [-][-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: json_decode() expects parameter 1 to be string, array given in /.../vendor/chasegiunta/craft-jason/src/fields/JasonField.php:432
Stack trace:
#0 /.../vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'json_decode() e...', '/home/...', 432)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'json_decode() e...', '/home/...', 432, Array)
#2 /.../vendor/chasegiunta/craft-jason/src/fields/JasonField.php(432): json_decode(Array)
#3 /.../vendor/craftcms/cms/src/base/Element.php(1383): chasegiunta\jason\fields\JasonField->validateIsJSON(Object(craft\elements\User), NULL)
#4 [internal function]: craft\base\Element->validateCustomFieldAttribute('field:subscrDat...', Array, Object(yii\validators\InlineValidator))
#5 /.../vendor/yiisoft/yii2/validators/InlineValidator.php(72): call_user_func(Array, 'field:subscrDat...', Array, Object(yii\validators\InlineValidator))
#6 /.../vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\User), 'field:subscrDat...')
#7 /.../vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\User), Array)
#8 /.../vendor/craftcms/cms/src/services/Elements.php(1987): yii\base\Model->validate()

```

I'm happy to create a PR for this if you can confirm this is the right approach to fix it.
Thanks.

**Comment by jerome2710** [comment]
@chasegiunta Could you please fix this? It seems like an easy fix.

**Comment by chasegiunta** [comment]
Thanks for digging into this @goraxan and sorry I haven't got to it sooner. I've been working an update to Jason the past couple of night and will have it out soon with this fix.

**Comment by chasegiunta** [comment]
Should be fixed now, thanks!
